[2024-02-26T16:28:47.721+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:28:46.151976+00:00 [queued]>
[2024-02-26T16:28:47.727+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:28:46.151976+00:00 [queued]>
[2024-02-26T16:28:47.727+0700] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T16:28:47.740+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-26 09:28:46.151976+00:00
[2024-02-26T16:28:47.742+0700] {standard_task_runner.py:60} INFO - Started process 30011 to run task
[2024-02-26T16:28:47.744+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-26T09:28:46.151976+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmp_7l45h5l']
[2024-02-26T16:28:47.746+0700] {standard_task_runner.py:88} INFO - Job 54: Subtask spark_ingestion_to_s3
[2024-02-26T16:28:47.802+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:28:46.151976+00:00 [running]> on host MinhNhut.
[2024-02-26T16:28:47.885+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T09:28:46.151976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T09:28:46.151976+00:00'
[2024-02-26T16:28:47.886+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-26T16:28:47.886+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ***/dags/missed_deadlinee_dag.py']
[2024-02-26T16:28:47.891+0700] {subprocess.py:86} INFO - Output:
[2024-02-26T16:28:47.907+0700] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmpe7a8faqa/***/dags/missed_deadlinee_dag.py': [Errno 2] No such file or directory
[2024-02-26T16:28:47.910+0700] {subprocess.py:97} INFO - Command exited with return code 2
[2024-02-26T16:28:47.924+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-02-26T16:28:47.927+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240226T092846, start_date=20240226T092847, end_date=20240226T092847
[2024-02-26T16:28:47.937+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 54 for task spark_ingestion_to_s3 (Bash command failed. The command returned a non-zero exit code 2.; 30011)
[2024-02-26T16:28:47.957+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T16:28:47.976+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
