[2024-02-27T12:03:08.723+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_transform_missed_deadline_job manual__2024-02-27T04:48:24.715240+00:00 [queued]>
[2024-02-27T12:03:08.729+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_transform_missed_deadline_job manual__2024-02-27T04:48:24.715240+00:00 [queued]>
[2024-02-27T12:03:08.730+0700] {taskinstance.py:2170} INFO - Starting attempt 2 of 1
[2024-02-27T12:03:08.741+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_transform_missed_deadline_job> on 2024-02-27 04:48:24.715240+00:00
[2024-02-27T12:03:08.743+0700] {standard_task_runner.py:60} INFO - Started process 27500 to run task
[2024-02-27T12:03:08.746+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_transform_missed_deadline_job', 'manual__2024-02-27T04:48:24.715240+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmp8ta49fnu']
[2024-02-27T12:03:08.748+0700] {standard_task_runner.py:88} INFO - Job 124: Subtask spark_transform_missed_deadline_job
[2024-02-27T12:03:08.801+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_transform_missed_deadline_job manual__2024-02-27T04:48:24.715240+00:00 [running]> on host MinhNhut.
[2024-02-27T12:03:08.885+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_transform_missed_deadline_job' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T04:48:24.715240+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-27T04:48:24.715240+00:00'
[2024-02-27T12:03:08.886+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-27T12:03:08.886+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/nhut/etl-***/pipeline/spark_missed_deadline_job.py']
[2024-02-27T12:03:08.890+0700] {subprocess.py:86} INFO - Output:
[2024-02-27T12:04:54.987+0700] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-02-27T12:04:54.990+0700] {process_utils.py:131} INFO - Sending 15 to group 27500. PIDs of all processes in the group: [27508, 27509, 27500]
[2024-02-27T12:04:54.990+0700] {process_utils.py:86} INFO - Sending the signal 15 to group 27500
[2024-02-27T12:04:54.990+0700] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-27T12:04:54.991+0700] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-02-27T12:04:54.993+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=27509, status='terminated', started='12:03:08') (27509) terminated with exit code None
[2024-02-27T12:04:55.008+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 203, in execute
    result = self.subprocess_hook.run_command(
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-27T12:04:55.010+0700] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=missed_deadline_job_dag, task_id=spark_transform_missed_deadline_job, execution_date=20240227T044824, start_date=20240227T050308, end_date=20240227T050455
[2024-02-27T12:04:55.025+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 124 for task spark_transform_missed_deadline_job (Task received SIGTERM signal; 27500)
[2024-02-27T12:04:55.045+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=27500, status='terminated', exitcode=1, started='12:03:08') (27500) terminated with exit code 1
[2024-02-27T12:04:55.046+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=27508, status='terminated', started='12:03:08') (27508) terminated with exit code None
