[2024-02-27T11:58:37.955+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_transform_missed_deadline_job manual__2024-02-27T04:28:02.034457+00:00 [queued]>
[2024-02-27T11:58:37.961+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_transform_missed_deadline_job manual__2024-02-27T04:28:02.034457+00:00 [queued]>
[2024-02-27T11:58:37.962+0700] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-02-27T11:58:37.973+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_transform_missed_deadline_job> on 2024-02-27 04:28:02.034457+00:00
[2024-02-27T11:58:37.976+0700] {standard_task_runner.py:60} INFO - Started process 24929 to run task
[2024-02-27T11:58:37.978+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_transform_missed_deadline_job', 'manual__2024-02-27T04:28:02.034457+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmpent36289']
[2024-02-27T11:58:37.979+0700] {standard_task_runner.py:88} INFO - Job 123: Subtask spark_transform_missed_deadline_job
[2024-02-27T11:58:38.031+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_transform_missed_deadline_job manual__2024-02-27T04:28:02.034457+00:00 [running]> on host MinhNhut.
[2024-02-27T11:58:38.111+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_transform_missed_deadline_job' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T04:28:02.034457+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-27T04:28:02.034457+00:00'
[2024-02-27T11:58:38.111+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-27T11:58:38.112+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/nhut/etl-***/pipeline/spark_missed_deadline_job.py']
[2024-02-27T11:58:38.116+0700] {subprocess.py:86} INFO - Output:
[2024-02-27T12:03:08.897+0700] {subprocess.py:93} INFO - import-im6.q16: unable to open X server `:0' @ error/import.c/ImportImageCommand/346.
[2024-02-27T12:03:08.921+0700] {subprocess.py:93} INFO - /home/nhut/etl-***/pipeline/spark_missed_deadline_job.py: line 2: from: command not found
[2024-02-27T12:03:08.940+0700] {subprocess.py:93} INFO - /home/nhut/etl-***/pipeline/spark_missed_deadline_job.py: line 3: from: command not found
[2024-02-27T12:03:08.959+0700] {subprocess.py:93} INFO - /home/nhut/etl-***/pipeline/spark_missed_deadline_job.py: line 4: $'\r': command not found
[2024-02-27T12:03:08.977+0700] {subprocess.py:93} INFO - /home/nhut/etl-***/pipeline/spark_missed_deadline_job.py: line 5: $'\r': command not found
[2024-02-27T12:03:08.977+0700] {subprocess.py:93} INFO - /home/nhut/etl-***/pipeline/spark_missed_deadline_job.py: line 6: syntax error near unexpected token `('
[2024-02-27T12:03:08.977+0700] {subprocess.py:93} INFO - /home/nhut/etl-***/pipeline/spark_missed_deadline_job.py: line 6: `def transform_data():'
[2024-02-27T12:03:08.978+0700] {subprocess.py:97} INFO - Command exited with return code 2
[2024-02-27T12:03:08.992+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-02-27T12:03:08.994+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_transform_missed_deadline_job, execution_date=20240227T042802, start_date=20240227T045837, end_date=20240227T050308
[2024-02-27T12:03:09.007+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 123 for task spark_transform_missed_deadline_job (Bash command failed. The command returned a non-zero exit code 2.; 24929)
[2024-02-27T12:03:09.016+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T12:03:09.033+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
